POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@example.com",
    "password": "password",
    "confirm_password": "password2"
}